### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by wellcaffeinated** [minutelabsio/Tree-of-Life-Explorer#40]
Both friends i showed the tree to, independently asked for a "zoom out" feature. 

Since building a zoom out feature that actually scales everything adds a lot of problems, I was wondering if maybe we could do one of the following:
- a "mini map" (like in games) http://goo.gl/E7qGHj
- a "simplified view" that compresses the cards down to a dot, and only shows the name if you click on it

@EverSalazar  Thoughts?

**Comment by EverSalazar** [comment]
I think that whoever is using this tree to show more than 10 species at a
time, don't really care too much about pictures or individual card
information, so I'd be interested to see a simplified version, maybe with
only shortened scientific names (or only common names). Of course, this
would only work in horizontal mode and will actually look very similar to
OTL (with the added functionality we have, of course). For this to work I
only see the lowest children names displayed and any parent node will just
be a dot or something like that.

The minimap idea is also interesting, but if a simplified version would be
a minimap on itself (which doesn't require more screen space)...

**Comment by EverSalazar** [comment]
Here you have three sketches of how I'm imagining this:

Sketch 1: 
![image](https://user-images.githubusercontent.com/23618796/47117557-11e62900-d23b-11e8-919e-28155acf2344.png)

Sketch 2:
![image](https://user-images.githubusercontent.com/23618796/47117568-1874a080-d23b-11e8-8f28-6a1baccc04ec.png)

Sketch 3:
![image](https://user-images.githubusercontent.com/23618796/47117575-1dd1eb00-d23b-11e8-898e-fd197455fbc3.png)

Both sketch 2 and 3 would work even if the branches are not extended to the same height. Also, the dots where the branches split would be the parent cards we have right now. I think 2 and 3 look really cool (and again, this would be useful for people that want more than 10 species at the same time)

Not sure if we should aim for those cases too, but I think they look cool enough to try, if possible. That could be a "simple version" of the tree that would probably remove the need for a zoomed version (or would make a zoom easier?)

And while we're here, what is the maximum length of an URL? seems like this can become a bit crazy. Do you think a "URL resolver" would make sense? Is it possible to build up "shortened" URLs by using hexadecimal numbers instead of decimal ones?, so instead of "&ids=ott351685" in the URL, we have something like: "&55DC5" where "55DC5" is just hexadecimal for whatever the ott number is.

**Comment by EverSalazar** [comment]
Here are some other screencaptures I had around (they're from Wikipedia) that might serve as inspiration, maybe?

![image](https://user-images.githubusercontent.com/23618796/47118313-4bb82f00-d23d-11e8-9743-8d763d3aaf6a.png)

![image](https://user-images.githubusercontent.com/23618796/47118327-51157980-d23d-11e8-9188-76521ceaf4e8.png)

![image](https://user-images.githubusercontent.com/23618796/47118350-5d013b80-d23d-11e8-8aa9-88989a170c76.png)

**Comment by wellcaffeinated** [comment]
<img width="1189" alt="screen shot 2018-10-23 at 2 15 52 pm" src="https://user-images.githubusercontent.com/1128935/47381564-56a41100-d6ce-11e8-879a-89531a1cc8e0.png">
How's this, @EverSalazar ?

**Comment by EverSalazar** [comment]
@wellcaffeinated YES! That looks great! It doesn't seem to be live, though, so I can't play with it.

I see dots on places different than the halfway point on the horizontal lines, which seems like something that can improve (unless there is a non-obvious reason why it is the way it is). Also, I'm under the impression that phylogeneticists don't like when the tips on the tree are not aligned at the same level (unless the level is conveying extinction or evolutionary change, for example). I'm not sure if I agree with them (or maybe I don't understand their concerns), but we should keep in mind this issue in case we need to fix it in the future (From now on, we can refer to this particular issue as "The cladogram problem". See [here](https://biology-forums.com/index.php?action=gallery;sa=view;id=5293) for a visual example)

**Comment by wellcaffeinated** [comment]
Ah interesting. I'd need to rewrite the whole tree placement algorithm to do that... so let's keep it like this for now.

Yeah the dots are weird right now. I'm not exactly sure what i want to implement.... should there be text? no dots? 

I'm thinking clicking somewhere will zoom to that place (so this is kind of a "map view" that just helps navigation)

**Comment by EverSalazar** [comment]
I like the dots (especially the ones at the tips, the ones in the middle can be removed and I won't feel like we lost something, however, I'm guessing they need to be there, since they refer to cards that are being displayed on-screen). 

If you could add text on the tips, that would be perfect. Either the Scientific Name or the Common Name (and be able to switch between the two, if possible). The text must be vertical, though (as in Sketch 2)

**Comment by wellcaffeinated** [comment]
Ok! I figured something out.
Check out the site. It'll have a little zoom button in the bottom right-hand corner
