### ISSUE TITLE
Searchs for certain superstar Mesozoic memorables miss: genera gone!

### ISSUE THREAD

**Issue by rockwalrus** [minutelabsio/Tree-of-Life-Explorer#61]
The search can't find Triceratops or Archaeopteryx.

**Comment by EverSalazar** [comment]
Thank you for taking the time to check the app and to submit this issue. **Most extinct creatures are indeed missing from the tree due to the difficulty of accurately establish ancestry for them ([incertae sedis](https://en.wikipedia.org/wiki/Incertae_sedis))**. So, we can have a lot of data on the species, but we cannot place them on the tree without a lot of uncertainty. Also remember we take our data from the Open Tree of Life project, and if they don't list the species, you won't find it here.

Also, keep in mind that a species can be listed in the taxonomy of the OTL (such as [Triceratops](https://tree.opentreeoflife.org/taxonomy/browse?name=Triceratops)) but still [isn't included in the synthetic](https://tree.opentreeoflife.org/opentree/argus/ottol@4947055) tree (meaning isn't on the tree as a branch)

@wellcaffeinated replied to this on #57
