### ISSUE TITLE
Mastodon doesn't work.

### ISSUE THREAD

**Issue by TitaniumSpyBorgBear** [minutelabsio/Tree-of-Life-Explorer#62]
Leaves a "Error: Request failed with status code 400" when you try to enter it in.

**Comment by EverSalazar** [comment]
Thanks for using ToLE and for leaving this report. Most extinct organisms are difficult to place on the tree due to lack of solid genetic evidence. The American Mastodon appears listed in the search results, because the database we use for searching is different than the one that contains only the organisms with a place in the tree. In the OTL page, you can see the organisms is listed on their [taxonomy](https://tree.opentreeoflife.org/taxonomy/browse?id=192377), but it isn't on the [tree](https://tree.opentreeoflife.org/opentree/argus/ottol@192377).

This happens also with extant organisms depending on their available phylogeny.
