### ISSUE TITLE
goats are bacteria?

### ISSUE THREAD

**Issue by GrayBuckley** [minutelabsio/Tree-of-Life-Explorer#71]
i was making a general collection of domestic animals and goats ("capra hicus") are categorized as a species of bacteria

**Comment by EverSalazar** [comment]
Hi, thanks for your report and for using the Tree of Life Explorer. Seems to be a mistake over at OTL, where we pull the taxonomic data from. They list "Capra Hircus" under bacteria ([here](https://tree.opentreeoflife.org/taxonomy/browse?id=5251869)), but the source seems to be a broken link, so it's probably a mistake. I'll try to report this to them, since there's nothing else we can do. As a workaround, try using [Capra or Caprinae](https://labs.minutelabs.io/Tree-of-Life-Explorer/#/?ids=ott122647&ids=mrcaott88864ott143624) for your tree.
